// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEstoque.API.Context;

#nullable disable

namespace SistemaEstoque.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250518050405_alteracaoTabelaUsuarioLicenca")]
    partial class alteracaoTabelaUsuarioLicenca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaEstoque.API.Models.CidadeModel", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.ClienteModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Cidadeid")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dthNascimeto")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("fAtivo")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.HasIndex("Cidadeid");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.EmpresaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LicencaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dthAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dthCadastro")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("LicencaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.EstadoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.FornecedoresModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dthAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dthCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("fAtivo")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.LicencaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid>("Licenca")
                        .HasColumnType("char(36)");

                    b.Property<int>("TipoLincenca")
                        .HasColumnType("int");

                    b.Property<int>("UsuairosIncluirFree")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosIncluidos")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorPorUsuario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("dthInicioLincenca")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dthVencimento")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Licencas");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.LogModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("InnerExecption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Messagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dthErro")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.LoginModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<bool>("fEmailConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("clienteId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.PedidoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Clienteid")
                        .HasColumnType("int");

                    b.Property<short>("Finalizado")
                        .HasColumnType("smallint");

                    b.Property<int>("Usuarioid")
                        .HasColumnType("int");

                    b.Property<DateTime>("dthPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("qtd")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Clienteid");

                    b.HasIndex("Usuarioid");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.PedidoXProduto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("ValorVenda")
                        .HasColumnType("float");

                    b.Property<int>("idPedido")
                        .HasColumnType("int");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<int>("qtd")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idPedido");

                    b.HasIndex("idProduto");

                    b.ToTable("PedidoXProdutos");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.ProdutoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Fornecedorid")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dthAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dthCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fAtivo")
                        .HasColumnType("int");

                    b.Property<int>("qtd")
                        .HasColumnType("int");

                    b.Property<int>("tipoProdutoid")
                        .HasColumnType("int");

                    b.Property<float>("valor")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Fornecedorid");

                    b.HasIndex("tipoProdutoid");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.TipoProdutoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("fAtivo")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("TpProdutos");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("dthCadastro")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.CidadeModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.EstadoModel", "Estado")
                        .WithMany("Cidade")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.ClienteModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.CidadeModel", "Cidade")
                        .WithMany()
                        .HasForeignKey("Cidadeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.EmpresaModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.CidadeModel", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.LicencaModel", "Licenca")
                        .WithMany()
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.FornecedoresModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.LoginModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaEstoque.API.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.PedidoModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.ClienteModel", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.PedidoXProduto", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.PedidoModel", "Pedido")
                        .WithMany("Produto")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.ProdutoModel", "Produto")
                        .WithMany("pedidos")
                        .HasForeignKey("idProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.ProdutoModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.FornecedoresModel", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("Fornecedorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.TipoProdutoModel", "tipoProduto")
                        .WithMany()
                        .HasForeignKey("tipoProdutoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Fornecedor");

                    b.Navigation("tipoProduto");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.TipoProdutoModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.UsuarioModel", b =>
                {
                    b.HasOne("SistemaEstoque.API.Models.CidadeModel", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaEstoque.API.Models.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.ClienteModel", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.EstadoModel", b =>
                {
                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.PedidoModel", b =>
                {
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaEstoque.API.Models.ProdutoModel", b =>
                {
                    b.Navigation("pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
